"""create backend foundation

Revision ID: 22eb9a0d4076
Revises:
Create Date: 2026-08-27 11:31:25.026132
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "22eb9a0d4076"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_username"), "profiles", ["username"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_entity_created",
        "audit_events",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "android",
                "ios",
                "web",
                "desktop",
                "api",
                "other",
                name="platform",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("public_summary", sa.String(length=800), nullable=False),
        sa.Column("public_tester_requirements", sa.String(length=800), nullable=False),
        sa.Column("minimum_version", sa.String(length=80), nullable=True),
        sa.Column("target_testers", sa.Integer(), nullable=False),
        sa.Column("reward_credits", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "published",
                "paused",
                "completed",
                "cancelled",
                name="campaign_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("reward_credits > 0", name="ck_campaign_reward_positive"),
        sa.CheckConstraint("target_testers > 0", name="ck_campaign_target_testers_positive"),
        sa.ForeignKeyConstraint(["owner_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_owner_id"), "campaigns", ["owner_id"], unique=False)
    op.create_index(op.f("ix_campaigns_slug"), "campaigns", ["slug"], unique=True)
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_index(
        "ix_campaigns_status_created", "campaigns", ["status", "created_at"], unique=False
    )
    op.create_table(
        "credit_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name="ck_credit_balance_nonnegative"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "credit_ledger_entries",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "signup_grant",
                "purchase",
                "reservation",
                "reward",
                "release",
                "refund",
                "adjustment",
                name="credit_entry_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reference_type", sa.String(length=80), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("delta != 0", name="ck_credit_delta_nonzero"),
        sa.ForeignKeyConstraint(["created_by"], ["profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_credit_ledger_entries_transaction_id"),
        "credit_ledger_entries",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_ledger_entries_user_id"), "credit_ledger_entries", ["user_id"], unique=False
    )
    op.create_index(
        "ix_credit_ledger_user_created",
        "credit_ledger_entries",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "assignments",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("tester_id", sa.Uuid(), nullable=False),
        sa.Column("application_note", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "applied",
                "accepted",
                "in_progress",
                "submitted",
                "changes_requested",
                "approved",
                "rejected",
                "cancelled",
                name="assignment_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tester_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "tester_id", name="uq_campaign_tester"),
    )
    op.create_index(
        op.f("ix_assignments_campaign_id"), "assignments", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_assignments_status"), "assignments", ["status"], unique=False)
    op.create_index(op.f("ix_assignments_tester_id"), "assignments", ["tester_id"], unique=False)
    op.create_index(
        "ix_assignments_tester_status", "assignments", ["tester_id", "status"], unique=False
    )
    op.create_table(
        "testing_contracts",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tester_instructions", sa.Text(), nullable=False),
        sa.Column("device_requirements", sa.Text(), nullable=True),
        sa.Column("evidence_requirements", sa.Text(), nullable=False),
        sa.Column("review_window_hours", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "locked", name="contract_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_testing_contracts_campaign_id"), "testing_contracts", ["campaign_id"], unique=True
    )
    op.create_table(
        "contract_tasks",
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("evidence_required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name="ck_contract_task_position_nonnegative"),
        sa.ForeignKeyConstraint(["contract_id"], ["testing_contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_id", "position", name="uq_contract_task_position"),
    )
    op.create_index(
        op.f("ix_contract_tasks_contract_id"), "contract_tasks", ["contract_id"], unique=False
    )
    op.create_table(
        "evidence_submissions",
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "changes_requested",
                "approved",
                "rejected",
                name="submission_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name="ck_submission_version_positive"),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "version", name="uq_assignment_submission_version"),
    )
    op.create_index(
        op.f("ix_evidence_submissions_assignment_id"),
        "evidence_submissions",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_submissions_status"), "evidence_submissions", ["status"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_assignment_created", "messages", ["assignment_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_table(
        "disputes",
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=True),
        sa.Column("opened_by", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "under_review",
                "resolved",
                "rejected",
                name="dispute_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["opened_by"], ["profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_by"], ["profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["evidence_submissions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_disputes_assignment_id"), "disputes", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_disputes_opened_by"), "disputes", ["opened_by"], unique=False)
    op.create_index(op.f("ix_disputes_status"), "disputes", ["status"], unique=False)
    op.create_index(
        "ix_disputes_status_created", "disputes", ["status", "created_at"], unique=False
    )
    op.create_table(
        "evidence_items",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "screenshot",
                "video",
                "log",
                "note",
                "link",
                "file",
                name="evidence_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("external_url", sa.String(length=1000), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "storage_key IS NOT NULL OR external_url IS NOT NULL OR note IS NOT NULL",
            name="ck_evidence_has_content",
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["evidence_submissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["contract_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_items_submission_id"), "evidence_items", ["submission_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_items_task_id"), "evidence_items", ["task_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "approved",
                "changes_requested",
                "rejected",
                name="review_decision",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["reviewer_id"], ["profiles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["evidence_submissions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_reviewer_id"), "reviews", ["reviewer_id"], unique=False)
    op.create_index(op.f("ix_reviews_submission_id"), "reviews", ["submission_id"], unique=True)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION prevent_credit_ledger_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'credit ledger entries are append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER credit_ledger_entries_immutable
            BEFORE UPDATE OR DELETE ON credit_ledger_entries
            FOR EACH ROW EXECUTE FUNCTION prevent_credit_ledger_mutation()
            """
        )
    elif op.get_bind().dialect.name == "sqlite":
        op.execute(
            """
            CREATE TRIGGER credit_ledger_entries_no_update
            BEFORE UPDATE ON credit_ledger_entries
            BEGIN
                SELECT RAISE(ABORT, 'credit ledger entries are append-only');
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER credit_ledger_entries_no_delete
            BEFORE DELETE ON credit_ledger_entries
            BEGIN
                SELECT RAISE(ABORT, 'credit ledger entries are append-only');
            END
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER credit_ledger_entries_immutable ON credit_ledger_entries")
        op.execute("DROP FUNCTION prevent_credit_ledger_mutation()")
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER credit_ledger_entries_no_update")
        op.execute("DROP TRIGGER credit_ledger_entries_no_delete")
    op.drop_index(op.f("ix_reviews_submission_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_reviewer_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_evidence_items_task_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_submission_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index("ix_disputes_status_created", table_name="disputes")
    op.drop_index(op.f("ix_disputes_status"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_opened_by"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_assignment_id"), table_name="disputes")
    op.drop_table("disputes")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index("ix_messages_assignment_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_evidence_submissions_status"), table_name="evidence_submissions")
    op.drop_index(op.f("ix_evidence_submissions_assignment_id"), table_name="evidence_submissions")
    op.drop_table("evidence_submissions")
    op.drop_index(op.f("ix_contract_tasks_contract_id"), table_name="contract_tasks")
    op.drop_table("contract_tasks")
    op.drop_index(op.f("ix_testing_contracts_campaign_id"), table_name="testing_contracts")
    op.drop_table("testing_contracts")
    op.drop_index("ix_assignments_tester_status", table_name="assignments")
    op.drop_index(op.f("ix_assignments_tester_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_status"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_campaign_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index("ix_credit_ledger_user_created", table_name="credit_ledger_entries")
    op.drop_index(op.f("ix_credit_ledger_entries_user_id"), table_name="credit_ledger_entries")
    op.drop_index(
        op.f("ix_credit_ledger_entries_transaction_id"), table_name="credit_ledger_entries"
    )
    op.drop_table("credit_ledger_entries")
    op.drop_table("credit_accounts")
    op.drop_index("ix_campaigns_status_created", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_slug"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_owner_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_index("ix_audit_entity_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_profiles_username"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
